
package services.QuestionClasses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QuestionServiceImplService", targetNamespace = "http://Services/", wsdlLocation = "http://localhost:1986/question?wsdl")
public class QuestionServiceImplService
    extends Service
{

    private final static URL QUESTIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUESTIONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName QUESTIONSERVICEIMPLSERVICE_QNAME = new QName("http://Services/", "QuestionServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1986/question?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUESTIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        QUESTIONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public QuestionServiceImplService() {
        super(__getWsdlLocation(), QUESTIONSERVICEIMPLSERVICE_QNAME);
    }

    public QuestionServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUESTIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public QuestionServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, QUESTIONSERVICEIMPLSERVICE_QNAME);
    }

    public QuestionServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUESTIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public QuestionServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuestionServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QuestionService
     */
    @WebEndpoint(name = "QuestionServiceImplPort")
    public QuestionService getQuestionServiceImplPort() {
        return super.getPort(new QName("http://Services/", "QuestionServiceImplPort"), QuestionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuestionService
     */
    @WebEndpoint(name = "QuestionServiceImplPort")
    public QuestionService getQuestionServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Services/", "QuestionServiceImplPort"), QuestionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUESTIONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw QUESTIONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return QUESTIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
