
package services.AnswerClasses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AnswerServiceImplService", targetNamespace = "http://Services/", wsdlLocation = "http://localhost:1986/answer?wsdl")
public class AnswerServiceImplService
    extends Service
{

    private final static URL ANSWERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ANSWERSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ANSWERSERVICEIMPLSERVICE_QNAME = new QName("http://Services/", "AnswerServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1986/answer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANSWERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ANSWERSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AnswerServiceImplService() {
        super(__getWsdlLocation(), ANSWERSERVICEIMPLSERVICE_QNAME);
    }

    public AnswerServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANSWERSERVICEIMPLSERVICE_QNAME, features);
    }

    public AnswerServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ANSWERSERVICEIMPLSERVICE_QNAME);
    }

    public AnswerServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANSWERSERVICEIMPLSERVICE_QNAME, features);
    }

    public AnswerServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnswerServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AnswerService
     */
    @WebEndpoint(name = "AnswerServiceImplPort")
    public AnswerService getAnswerServiceImplPort() {
        return super.getPort(new QName("http://Services/", "AnswerServiceImplPort"), AnswerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnswerService
     */
    @WebEndpoint(name = "AnswerServiceImplPort")
    public AnswerService getAnswerServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Services/", "AnswerServiceImplPort"), AnswerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANSWERSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ANSWERSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ANSWERSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
