
package services.QuestionareClasses;

import services.QuestionareClasses.OuestionareService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QuestionareServiceImplService", targetNamespace = "http://Services/", wsdlLocation = "http://localhost:1986/questionare?wsdl")
public class QuestionareServiceImplService
    extends Service
{

    private final static URL QUESTIONARESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUESTIONARESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName QUESTIONARESERVICEIMPLSERVICE_QNAME = new QName("http://Services/", "QuestionareServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1986/questionare?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUESTIONARESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        QUESTIONARESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public QuestionareServiceImplService() {
        super(__getWsdlLocation(), QUESTIONARESERVICEIMPLSERVICE_QNAME);
    }

    public QuestionareServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUESTIONARESERVICEIMPLSERVICE_QNAME, features);
    }

    public QuestionareServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, QUESTIONARESERVICEIMPLSERVICE_QNAME);
    }

    public QuestionareServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUESTIONARESERVICEIMPLSERVICE_QNAME, features);
    }

    public QuestionareServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuestionareServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OuestionareService
     */
    @WebEndpoint(name = "QuestionareServiceImplPort")
    public OuestionareService getQuestionareServiceImplPort() {
        return super.getPort(new QName("http://Services/", "QuestionareServiceImplPort"), OuestionareService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OuestionareService
     */
    @WebEndpoint(name = "QuestionareServiceImplPort")
    public OuestionareService getQuestionareServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Services/", "QuestionareServiceImplPort"), OuestionareService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUESTIONARESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw QUESTIONARESERVICEIMPLSERVICE_EXCEPTION;
        }
        return QUESTIONARESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
