
package services.RoleClasses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RoleServiceImplService", targetNamespace = "http://Services/", wsdlLocation = "http://localhost:1986/role?wsdl")
public class RoleServiceImplService
    extends Service
{

    private final static URL ROLESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROLESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ROLESERVICEIMPLSERVICE_QNAME = new QName("http://Services/", "RoleServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1986/role?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROLESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ROLESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RoleServiceImplService() {
        super(__getWsdlLocation(), ROLESERVICEIMPLSERVICE_QNAME);
    }

    public RoleServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROLESERVICEIMPLSERVICE_QNAME, features);
    }

    public RoleServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ROLESERVICEIMPLSERVICE_QNAME);
    }

    public RoleServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROLESERVICEIMPLSERVICE_QNAME, features);
    }

    public RoleServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoleServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RoleService
     */
    @WebEndpoint(name = "RoleServiceImplPort")
    public RoleService getRoleServiceImplPort() {
        return super.getPort(new QName("http://Services/", "RoleServiceImplPort"), RoleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RoleService
     */
    @WebEndpoint(name = "RoleServiceImplPort")
    public RoleService getRoleServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Services/", "RoleServiceImplPort"), RoleService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROLESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ROLESERVICEIMPLSERVICE_EXCEPTION;
        }
        return ROLESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
